### ISSUE TITLE
end-0 cannot be applied

### ISSUE THREAD

**Issue by ManuBernard** [20lives/tailwindcss-rtl#13]
Hi, 

The utility class end-0 won't work if used in an apply directive. 
It works when used in the html. 

![image](https://user-images.githubusercontent.com/1818934/100614444-70d16400-3316-11eb-987a-e7c1d5349870.png)

Other utilities like pe-0 or ms-10 works when applied. 

Is this something known ?

**Comment by 20lives** [comment]
hi,
what version of tailwind are you using?

**Comment by 20lives** [comment]
There was an issue with tailwind itself not supporting complex utilities with `@apply`, this was supposed to be fixed on of the latest versions of a tailwind but I never tested it myself.
I recommend you test it on 2.0.1 or at least 1.9.x

**Comment by ManuBernard** [comment]
Thank you for your response, I'am using Tailwind 1.7.6.

**Comment by ManuBernard** [comment]
Sounds like it's not working with tailwind v 1.9.6.
We don't want to migrate to tailwind 2.x since we need to stay compatible
with ie 11.

You think there is a way to use @apply end-0 with tailwind 1.9.6 ?

**Comment by 20lives** [comment]
I don't think so, you will have to use it directly in the tag class property.

and by the way, you will also have to use older version of **tailwindcss-rtl** because ie support was also removed.
