### ISSUE TITLE
Cannot create 1px borders with border-s and border-e

### ISSUE THREAD

**Issue by mattlangeman** [20lives/tailwindcss-rtl#16]
First, thanks for this tailwind plugin. I like the approach for making tailwind support right to left languages.

I ran into an issue creating 1px width borders using border-s and border-e.

In tailwind I can use border-l to create a 1px border on the left of a container. Similar with border-r. However, border-s and border-e does not behave this way.

My options are:
  - Create 2px border with border-s-2
  - Use this to set border and remove other sides "border border-e-0 border-t-0 border-b-0"

**Comment by 20lives** [comment]
this should work, let me check it.

**Comment by 20lives** [comment]
Everything seems to be in place:
![image](https://user-images.githubusercontent.com/8869390/103316296-b9bd2b00-4a30-11eb-8975-85b2f286e564.png)

Can you upload a demo or screenshot of the problem?

**Comment by mattlangeman** [comment]
Interesting. I looked at the generated stylesheet and found the following rules:

```
.border-s-0 {
  border-inline-start-width: 0px;
}

.border-e-2 {
  border-inline-end-width: 2px;
}

.border-s-2 {
  border-inline-start-width: 2px;
}

.border-e-4 {
  border-inline-end-width: 4px;
}

.border-s-4 {
  border-inline-start-width: 4px;
}

.border-e-8 {
  border-inline-end-width: 8px;
}

.border-s-8 {
  border-inline-start-width: 8px;
}

.border-e-DEFAULT {
  border-inline-end-width: 1px;
}

.border-s-DEFAULT {
  border-inline-start-width: 1px;
}

```

I'm not sure why I'm seeing -DEFAULT for the 1px width rules.

**Comment by 20lives** [comment]
what versions of **tailwindcss** and **tailwindcss-rtl** are you using?

**Comment by mattlangeman** [comment]
tailwindcss: 2.0.1
tailwindcss-rtl: 0.7.1

I am using [django-tailwind](https://github.com/timonweb/django-tailwind) but my understanding is that it is essentially a wrapper around the npm stuff.

**Comment by 20lives** [comment]
Found it, this seems to be some incompatibility with v2, I will try to fix this soon.
Thanks.

**Comment by 20lives** [comment]
If this is critical you can downgrade to 1.9.6 for now.

**Comment by mattlangeman** [comment]
Thanks. This is not critical. My new workaround is just using border-s-DEFAULT or border-e-DEFAULT. I see this affects other utilities. In my digging I ran into [this merged pull request](https://github.com/tailwindlabs/tailwindcss/pull/2580) which I'm guessing you also found.

**Comment by 20lives** [comment]
pretty simple fix, should have done this earlier.

thanks.
