### ISSUE TITLE
Position absolute/relative `left` and `right` values

### ISSUE THREAD

**Issue by z-x** [20lives/tailwindcss-rtl#19]
It might be a good idea to have an utility class that would replace `left` and `right` CSS values. It is a common thing to need to reverse those in RTL designs. Something like `end-auto`, `end-0` and `start-auto` `start-0` maybe?

**Comment by 20lives** [comment]
This is a great idea!
Fortunately :laughing: these utilities already exist in the plugin just missing from the docs.

**Comment by z-x** [comment]
Found them in the code! :D
