### ISSUE TITLE
Generator for insetUtilities doesn't seem to work

### ISSUE THREAD

**Issue by randriese** [20lives/tailwindcss-rtl#20]
We're using tailwindcss-rtl, but for some reason the insetUtilities aren't being loaded.
As a result, when we apply the start-0 modifier in our CSS, the build phase will throw the following error:

`(49:0) `@apply` cannot be used with `.start-0` because `.start-0` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.start-0` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.`

For other classes, like the padding utilities, it all works fine and as expected.
Any idea where to look?

**Comment by 20lives** [comment]
Hi,
What versions of tailwindcss and tailwindcss-rtl are you using?

**Comment by randriese** [comment]
Hi,

I'm using Tailwindcss version 1.9.6 and tailwindcss-rtl version 0.7.3.

All other utility classes are working, only the inset utilities aren't working when @applying them in the styling.

**Comment by 20lives** [comment]
There are two types of utility implementations in this plugin, the first is with bidirectional properties and the other with attribute selectors.
personally, I have never tried using the @apply, but I know there were issues with complex selectors (the attribute selectors).

tailwindcss 2.0 has improved support for @apply so I would start with that. otherwise, you will probably have to use the inline structure.

**Comment by randriese** [comment]
But how is it possible that ps-4 works, but start-4 doesn't. They shouldn't differ that much, right ?

**Comment by 20lives** [comment]
As I mentioned before the utilities below are supported without any issues, all others note:
- borderRadiusUtilities
- borderWidthUtilities 
- divideUtilities
- floatUtilities
- marginUtilities
- paddingUtilities
- spaceUtilities

And please share your solution as this problem rise here once in a while..

**Comment by randriese** [comment]
My solution for now was to simply make the direction distinction in the scoped styling.
So instead of doing this:

.someclass::before {
  @apply start-0;
}

I'm doing this:
[dir='ltr'] .someclass::before {
  @apply left-0;
}
[dir='rtl'] .someclass::before {
  @apply right-0;
}
