### ISSUE TITLE
rounded-* classes don't work at all

### ISSUE THREAD

**Issue by VSG24** [20lives/tailwindcss-rtl#23]
None of them really work. They don't generate the appropriate classes.

**Comment by 20lives** [comment]
Just checked it again, I don't find any issue.
what tailwindcss and tailwindcss-rtl versions are you using?
and can you give me additional info about your work setup?

**Comment by VSG24** [comment]
My locale is English and every other class RTL class works fine including `ps-*` and `pe-*` classes however replacing `rounded-l-md` with `rounded-s-md` should logically give the same result but it doesn't generate anything.

**Comment by 20lives** [comment]
![image](https://user-images.githubusercontent.com/8869390/109393918-01770a80-792d-11eb-8695-e858c775abd6.png)
this was taken from the generated file on 0.7.3.

**Comment by VSG24** [comment]
My bad, I wasn't setting the right direction attribute in the main html tag. Setting `dir="ltr"` to <html> fixed the problems.
