### ISSUE TITLE
How to use responsive variants for this plugin's utilities?

### ISSUE THREAD

**Issue by meirroth** [20lives/tailwindcss-rtl#33]
Like this for example: `<h1 class="text-center lg:text-start">Hello World</h1>`

**Comment by 20lives** [comment]
exactly as you did there, the following show change between each breakpoint
```
<h1 class="text-center text-start sm:text-end md:text-start lg:text-end">Hello World</h1>
```

**Comment by meirroth** [comment]
Yes, I realized I was missing a dir attributed on the html tag, and I think that’s why it wasn’t working. 

All good now! Thanks.
