### ISSUE TITLE
Spaceing

### ISSUE THREAD

**Issue by MuhamadSelim** [20lives/tailwindcss-rtl#4]
Thanks for this plugin really helpful .
space-x-  isn't supported always  margin-left is there a work around?

**Comment by 20lives** [comment]
Better than a workaround, a fix is waiting to be merged in the official release: https://github.com/tailwindlabs/tailwindcss/pull/1883

It might speed things up if people show it's needed.

**Comment by 20lives** [comment]
the new added alternative utilities will solve this issue:

divide-x ---> divide-s
divide-x-8 ---> divide-s-8
space-x ---> space-s
space-x-4 ---> space-s-4
