### ISSUE TITLE
tailwind-rtl not working when the parent dir="rtl" in version 0.8.0

### ISSUE THREAD

**Issue by lord007tn** [20lives/tailwindcss-rtl#41]
I had a problem with tailwind-rtl version 0.8.0.

everything works fine in LTR mode but when I change the direction the pseudo selector :not([dir="rtl"]) keep working and cause the element to apply CSS to both directions - start and end - .

I manage to have a fixed solution by going to the previous version 0.7.2

I noticed that in version 0.8.0 the CSS class are like that :
```

@media (min-width: 768px) {
    :not([dir="rtl"]) .md\:rounded-ts-huge {
        border-top-left-radius: 150px;
    }
}
@media (min-width: 768px) {
    [dir="rtl"] .md\:rounded-ts-huge {
        border-top-right-radius: 150px;
    }
}
```
but in version 0.7.2 

```
@media (min-width: 768px) {
    ([dir="ltr"]) .md\:rounded-ts-huge {
        border-top-left-radius: 150px;
    }
}
@media (min-width: 768px) {
    [dir="rtl"] .md\:rounded-ts-huge {
        border-top-right-radius: 150px;
    }
}
```

I believe that this causes the problem.

my env is:
angular version 13.
scss
tailwindcss@latest

**Comment by 20lives** [comment]
I also noticed this issue.

the `:not()` class will not match parents, but only the element itself.

I can't find a proper solution so I guess I will have to revert this.

**Comment by Ali-Javanmardi** [comment]
I have same issue after this update and for three days I was investigating on other components as tailwindcss-rtl was working perfectly before this update.

**Comment by mahdi-marjani-moghadam** [comment]
when use rtl in body divide-x don't work

![image](https://user-images.githubusercontent.com/22039262/145708409-cc3e0127-53d4-49d5-a8bf-a8fb6aea130f.png)

border left display on last item

**Comment by ShaneParkerCXP** [comment]
hmm... so v0.8.0 will only work if the `dir` attribute is set on **_all_** ancestors, to stop `:not([dir="rtl"])` from matching.

But then the previous versions would always require an explicit `dir="..."` for all those rules that depend on it to work (`inset`, `transformOrigin`, `float`, etc), which does not follow default browser behaviour so also not ideal.

How about exposing a plugin option that switches between 2 behaviours:

1. The consumer ensures that they always define the `dir` attribute at some point in the ancestry for these dependant rules to function (as with <= v0.7.3).

**OR**

2. Behaviour defaults to LTR, but the consumer has the option of adding `dir="rtl"` to the `body` element (only) to switch to RTL,  e.g.:

```
  'body[dir="rtl"] .text-start': { 'text-align': 'right' },
  'body[dir="rtl"] .text-end': { 'text-align': 'left' },
  'body:not([dir="rtl"]) .text-end': { 'text-align': 'right' },
  'body:not([dir="rtl"]) .text-start': { 'text-align': 'left' },
```

Option 2 would suit the majority of use cases I have seen, but appreciate that making this the **only** way would be too opinionated, and would preclude the consumer from rendering a page with mixed directionality.

**Comment by 20lives** [comment]
fixed.
