### ISSUE TITLE
Plugin doesn't work with Tailwind v3

### ISSUE THREAD

**Issue by dhruvkb** [20lives/tailwindcss-rtl#42]
Running this plugin with Tailwind 3 in a Nuxt project gives the following error:

```
TypeError: Cannot read properties of undefined (reading 'parent')
```

The plugins documentation on Tailwind mentions different parameters to the `plugin()` function between [v2](https://v2.tailwindcss.com/docs/plugins) and [v3](https://tailwindcss.com/docs/plugins), notably the absence of `variants` param (which makes sense considering that all variants are enabled by default in the JIT engine).

**Comment by danharrin** [comment]
Tailwind 3 has RTL support out of the box - you don't need this plugin.

**Comment by dhruvkb** [comment]
I was kind of hoping they'd provide start/end utilities but they instead went with variants to use with the existing left/right utilities. Either way , thanks for the heads up @danharrin. Feel free to close the issue.

**Comment by Reex11** [comment]
I want to use this plugin, I dont like the way Tailwindcss used to support RTL

**Comment by 20lives** [comment]
I agree that the integrated solution is not as useful as this, it existed as a plugin before this one existed.

i will look into how to add support for v3 (there is another issue with relevant info)

**Comment by 20lives** [comment]
Just tested the plugin with Tailwind3, all the utilities work with no issue.

if there is an issue, please reopen :smile:
