### ISSUE TITLE
right-* left-* classes to be start-* and end-*

### ISSUE THREAD

**Issue by YoussefZidan** [20lives/tailwindcss-rtl#55]
Is there a fix for the `right-*` and `left-*` classes?

My suggestion is to change the keywords `right` and `left` to `end` and `start` respectively.

In this manner, the classes will be labelled `start-3,` `end-4,` etc.

Alternately, just switch `Right/Left` according to the parent's direction. 

Currently, the solution I came up with is:

```jsx
<div className="ltr:right-3 rtl:left-3" />
```

**Comment by aliazizi** [comment]
> Is there a fix for the `right-*` and `left-*` classes?
> 
> My suggestion is to change the keywords `right` and `left` to `end` and `start` respectively.
> 
> In this manner, the classes will be labelled `start-3,` `end-4,` etc.
> 
> Alternately, just switch `Right/Left` according to the parent's direction.
> 
> Currently, the solution I came up with is:
> 
> ```js
> <div className="ltr:right-3 rtl:left-3" />
> ```

This is actually is in this library.
You can use `start-3` and `end-4` right now.
