### ISSUE TITLE
Does this package support latest version of TailwindCSS v3.4.13

### ISSUE THREAD

**Issue by yabasha** [20lives/tailwindcss-rtl#68]
Does the tailwindcss-rtl package support the latest version of TailwindCSS (v3.4.13)? I'm starting a new multilingual project and want to ensure compatibility.

**Comment by mbsoft31** [comment]
hi, 
Tailwindcss already have this feature and you don't need this package anymore.
see this [https://tailwindcss.com/blog/tailwindcss-v3#rtl-and-ltr-modifiers](https://tailwindcss.com/blog/tailwindcss-v3#rtl-and-ltr-modifiers)
